package fworks.algorithms.api.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Sorting Request model.
 * @author flaviolcastro
 *
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document
public class SortingRequest {

  /**
   * Generated id.
   */
  @Id
  private String id;
  
  /**
   * Array to be sorted.
   */
  private long[] array;
  
  /**
   * Responses generated by the request.
   */
  private SortingResponse[] responses;

}
