package fworks.algorithms.searching.model.searchrequest;

import fworks.algorithms.jpa.JsonConverter;
import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OrderColumn;
import javax.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Search Request model.
 * 
 * @author flaviolcastro
 *
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class SearchRequest {

  /**
   * Generated id.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long id;

  /**
   * Key to be found.
   */
  @NotNull
  @Column(name = "search_key", nullable = false)
  private long key;

  /**
   * Array to be searched.<br>
   * Converter to json to be saved on the db.
   */
  @Lob
  @NotNull
  @Column(nullable = false)
  @Convert(converter = JsonConverter.class)
  private long[] array;

  /**
   * Responses generated by the request.
   */
  @Column(nullable = false)
  @ElementCollection
  @OrderColumn
  private SearchResponse[] responses;

}
